import { parseIssue, issueUrl, issuesFromHub, issuesWire, issueCount } from './requirement-issues';
import { requirementFromHub } from './requirements-hub';
import { patchApplied } from './task-board-model';
import { readFileSync } from 'node:fs';
let p=0,t=0;const ck=(name:string,ok:boolean)=>{t++;if(ok)p++;console.log(`${ok?'PASS':'FAIL'} ${name}`);};
for(const input of [' acme/repo#001 ','https://github.com/acme/repo/issues/1/']) ck('canonical '+input,issueUrl(parseIssue(input)!)==='https://github.com/acme/repo/issues/1');
for(const input of ['http://github.com/a/b/issues/1','https://github.com.evil/a/b/issues/1','https://github.com/a/b/pull/1','https://github.com/a/b/issues/1?q=x','https://github.com/a/b/issues/1#x','a/b#0','a/b#10000001','a/b#-1','a/b#1.1','a/b#1\nfoo','https://u@github.com/a/b/issues/1']) ck('reject '+input,!parseIssue(input));
ck('upper range accepted',!!parseIssue('a/b#10000000'));
ck('source must be URL not shorthand',!parseIssue('a/b#1',false));
const issues=issuesFromHub([{repo:'a/b',number:1,title:'user title'},'https://github.com/a/b/issues/1']);
ck('read normalized objects, preserve title, dedup',issues?.length===1&&issues[0].title==='user title');
ck('wire is canonical and preserves titles',JSON.stringify(issuesWire(issues!))==='[{"url":"https://github.com/a/b/issues/1","title":"user title"}]');
ck('missing/malformed issues not treated as empty',issuesFromHub(null)===undefined&&issuesFromHub(['bad'])===undefined);
ck('empty supported',issuesFromHub([])?.length===0);
ck('same eight-item bound as Hub',issuesFromHub(Array.from({length:8},(_,i)=>`https://github.com/a/b/issues/${i+1}`))?.length===8&&issuesFromHub(Array.from({length:9},(_,i)=>`https://github.com/a/b/issues/${i+1}`))===undefined);
const row=requirementFromHub({id:'r',name:'Task',issues,external_ref:'github:a/b#1',external_url:'https://github.com/a/b/issues/1'})!;
ck('GET keeps manual links separate from sync identity',row.issues?.length===1&&row.externalRef==='github:a/b#1');
ck('count distinct union of manual and source',issueCount(row)===1&&issueCount({...row,externalUrl:'https://github.com/a/b/issues/2'})===2);
ck('PATCH verified against acknowledgement',patchApplied(row,{issues:issuesWire(issues!)})&&!patchApplied({...row,issues:undefined},{issues:[]})&&!patchApplied(row,{issues:[]}));
ck('no issues patch leaves associations alone',patchApplied(row,{name:'Task'}));
const component=readFileSync(new URL('./TaskIssueBindings.tsx',import.meta.url),'utf8');
ck('single open-external exit',component.includes('openExternal(issueUrl(issue))')&&!component.includes('Linking.openURL'));
ck('write only issues; source not writable',component.includes('onSave({ issues: issuesWire(next) })')&&!component.includes('external_ref:')&&!component.includes('external_url:'));
ck('sync guard and unmount guard present',component.includes('busy.current = true')&&component.includes('if (!live.current) return'));
console.log(`${p}/${t} passed`);process.exit(p===t?0:1);
