import { defaultFields, FIELD_IDS, FIELDS_KEY, loadFields, moveField, parseFields, saveFields, toggleField } from './task-list-fields';
import { readFileSync } from 'node:fs';
let p = 0, t = 0;
const ck = (name: string, ok: boolean) => { t++; if (ok) p++; console.log(`${ok ? 'PASS' : 'FAIL'}: ${name}`); };
ck('complete catalog', defaultFields().length === FIELD_IDS.length);
ck('secondary columns hidden', defaultFields().filter(f => !f.visible).map(f => f.id).join() === 'participants,issues,tags');
for (const raw of [null, '{', '{}', 'false', '[null,4,"x"]']) ck(`invalid preference ${raw}`, parseFields(raw).length === FIELD_IDS.length);
const repaired = parseFields('[{"id":"title","visible":false},{"id":"owner","visible":false},{"id":"owner"},{"id":"bogus"}]');
ck('title always visible', repaired.find(f => f.id === 'title')!.visible);
ck('deduplicates and rejects unknown fields', repaired.length === FIELD_IDS.length);
ck('preserves hidden column', !repaired.find(f => f.id === 'owner')!.visible);
ck('title toggle locked', toggleField(defaultFields(), 'title').find(f => f.id === 'title')!.visible);
ck('toggle participant', toggleField(defaultFields(), 'participants').find(f => f.id === 'participants')!.visible);
const moved = moveField(defaultFields(), 'status', 'owner');
const at = (list: { id: string }[], id: string) => list.findIndex(f => f.id === id);
ck('move order', at(moved, 'status') === at(defaultFields(), 'owner') && at(moved, 'owner') === at(defaultFields(), 'owner') + 1);
ck('move does not mutate defaults', defaultFields().map(f => f.id).join() === FIELD_IDS.join());
ck('round trip', JSON.stringify(parseFields(JSON.stringify(moved))) === JSON.stringify(moved));
ck('future field appended with default', parseFields('[{"id":"title","visible":true}]').find(f => f.id === 'issues')?.visible === false);
let stored = '';
Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { getItem: () => null, setItem: (key: string, raw: string) => { if (key === FIELDS_KEY) stored = raw; } } });
saveFields(moved);
ck('device preference stored', stored === JSON.stringify(moved));
ck('session snapshot', JSON.stringify(loadFields()) === stored);
Object.defineProperty(globalThis, 'localStorage', { configurable: true, get: () => { throw new Error('denied'); } });
saveFields(defaultFields());
ck('denied storage preserves usable preference', loadFields().map(f => f.id).join() === FIELD_IDS.join());
const board = readFileSync(new URL('./RequirementBoard.tsx', import.meta.url), 'utf8').replace(/\r\n?/g, '\n');
const list = board.slice(board.indexOf('const list = () =>'), board.indexOf('const body ='));
ck('list layout branches on width only, not pointer', /if \(narrow\)/.test(list) && !/if \([^)]*!pointer/.test(list));
const ui = readFileSync(new URL('./TaskListFields.tsx', import.meta.url), 'utf8').replace(/\r\n?/g, '\n');
ck('touch gets named up/down controls and no keyboard autofocus', ui.includes("'fields.up' : 'fields.down'") && ui.includes('autoFocus={!touch}'));
console.log(`${p}/${t} passed`); if (p !== t) process.exit(1);
